spring:
  application:
    name: oar-server
    version: 0.1.0
  threads:
    virtual:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-ttl: 15m
    refresh-token-ttl: 30d
  google:
    client-id: ${GOOGLE_CLIENT_ID}
