package dev.ridill.oar_server.user;

/**
 * How a {@link UserKeyWrap}'s key-encryption key was derived on the client.
 * <p>
 * The distinction matters cryptographically: {@code GENERATED_PHRASE} is
 * high-entropy and generated by the client, so a cheap KDF is sufficient.
 * {@code USER_PASSWORD} would be human-chosen and requires a memory-hard KDF
 * with aggressive parameters, since the stored blob is offline-crackable.
 */
public enum WrapMethod {
    GENERATED_PHRASE,
    USER_PASSWORD
}
